version: '3'
services:
  api:
    image: node:16.17.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./
        target: /code

  db:
    image: postgres:12.4
    environment: 
      - POSTGRES_USER=futureproof
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d/:ro"